In [100]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings("ignore")
from sklearn.base import BaseEstimator, TransformerMixin

In [81]:
df = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
test.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
5,FDH56,9.800,Regular,0.063817,Fruits and Vegetables,117.1492,OUT046,1997,Small,Tier 1,Supermarket Type1
6,FDL48,19.350,Regular,0.082602,Baking Goods,50.1034,OUT018,2009,Medium,Tier 3,Supermarket Type2
7,FDC48,NaN,Low Fat,0.015782,Baking Goods,81.0592,OUT027,1985,Medium,Tier 3,Supermarket Type3
8,FDN33,6.305,Regular,0.123365,Snack Foods,95.7436,OUT045,2002,NaN,Tier 2,Supermarket Type1
9,FDA36,5.985,Low Fat,0.005698,Baking Goods,186.8924,OUT017,2007,NaN,Tier 2,Supermarket Type1
10,FDT44,16.600,Low Fat,0.103569,Fruits and Vegetables,118.3466,OUT017,2007,NaN,Tier 2,Supermarket Type1
11,FDQ56,6.590,Low Fat,0.105811,Fruits and Vegetables,85.3908,OUT045,2002,NaN,Tier 2,Supermarket Type1
12,NCC54,NaN,Low Fat,0.171079,Health and Hygiene,240.4196,OUT019,1985,Small,Tier 1,Grocery Store
13,FDU11,4.785,Low Fat,0.092738,Breads,122.3098,OUT049,1999,Medium,Tier 1,Supermarket Type1
14,DRL59,16.750,LF,0.021206,Hard Drinks,52.0298,OUT013,1987,High,Tier 3,Supermarket Type1
15,FDM24,6.135,Regular,0.079451,Baking Goods,151.6366,OUT049,1999,Medium,Tier 1,Supermarket Type1
16,FDI57,19.850,Low Fat,0.054135,Seafood,198.7768,OUT045,2002,NaN,Tier 2,Supermarket Type1
17,DRC12,17.850,Low Fat,0.037981,Soft Drinks,192.2188,OUT018,2009,Medium,Tier 3,Supermarket Type2
18,NCM42,NaN,Low Fat,0.028184,Household,109.6912,OUT027,1985,Medium,Tier 3,Supermarket Type3
19,FDA46,13.600,Low Fat,0.196898,Snack Foods,193.7136,OUT010,1998,NaN,Tier 3,Grocery Store

In [78]:
df.loc[df["Item_Identifier"] == "NCM42", ["Item_Identifier", "Item_Weight"]]

     Item_Identifier  Item_Weight
1140           NCM42         6.13
6422           NCM42         6.13

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [33]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

### Category: Item_Identifier, Item_Fat_Content, Item_Type, Outlet_Identifier, Outlet_Size, Outlet_Location_Type, Outlet_Type
### Numerical: Item_Weight, Item_Visibility, Item_MRP, Item_Outlet_Sales
### Year: Outlet_Establishment_Year

In [34]:
print(df.describe())

       Item_Weight  Item_Visibility     Item_MRP  Outlet_Establishment_Year  \
count  7060.000000      8523.000000  8523.000000                8523.000000
mean     12.857645         0.066132   140.992782                1997.831867
std       4.643456         0.051598    62.275067                   8.371760
min       4.555000         0.000000    31.290000                1985.000000
25%       8.773750         0.026989    93.826500                1987.000000
50%      12.600000         0.053931   143.012800                1999.000000
75%      16.850000         0.094585   185.643700                2004.000000
max      21.350000         0.328391   266.888400                2009.000000

       Item_Outlet_Sales
count        8523.000000
mean         2181.288914
std          1706.499616
min            33.290000
25%           834.247400
50%          1794.331000
75%          3101.296400
max         13086.964800

In [43]:
df.apply(lambda x: len(x.unique()))

Item_Identifier              1559
Item_Weight                   416
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     4
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [96]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [90]:
# Create a pivot table of the most frequent Outlet_Size for each Outlet_Type
outlet_size_mode = df.pivot_table(
    values="Outlet_Size", 
    index="Outlet_Type", 
    aggfunc=lambda x: x.mode()[0]
)

print(outlet_size_mode)

                  Outlet_Size
Outlet_Type
Grocery Store           Small
Supermarket Type1       Small
Supermarket Type2      Medium
Supermarket Type3      Medium

In [95]:
df["Item_Weight"].fillna(df["Item_Weight"].median(), inplace=True)

In [93]:
# Fill missing values using Outlet_Type mapping
df.loc[df["Outlet_Size"].isnull(), "Outlet_Size"] = (df.loc[df["Outlet_Size"].isnull(), "Outlet_Type"].map(outlet_size_mode["Outlet_Size"]))

In [94]:
print(df["Outlet_Size"].isnull().sum())

0

In [47]:
c_col = []
for x in df.dtypes.index:
    if df.dtypes[x]  ==  "object":
        c_col.append(x)
c_col

['Item_Identifier',
 'Item_Fat_Content',
 'Item_Type',
 'Outlet_Identifier',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [58]:
# c_col.remove('Item_Identifier')
# c_col.remove('Outlet_Identifier')
for col in c_col:
    print(col)
    print(df[col].value_counts())
    print()

Item_Fat_Content
Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: count, dtype: int64

Item_Type
Item_Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: count, dtype: int64

Outlet_Size
Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64

Outlet_Location_Type
Outlet_Location_Type
Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: count, dtype: int64

Outlet_Type
Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64

In [79]:
df["Item_Weight"].fillna(df.groupby("Item_Identifier")["Item_Weight"].transform("mean"), inplace=True)

In [97]:
# Mapping dictionary
size_mapping = {
    ("Tier 1", "Grocery Store"): "Small",
    ("Tier 1", "Supermarket Type1"): "Medium",
    ("Tier 2", "Supermarket Type1"): "Small",
    ("Tier 3", "Grocery Store"): "Small",   # <-- you can decide here (replace NaN with Small)
    ("Tier 3", "Supermarket Type1"): "High",
    ("Tier 3", "Supermarket Type2"): "Medium",
    ("Tier 3", "Supermarket Type3"): "Medium",
}

# Apply mapping
df["Outlet_Size"] = df.apply(
    lambda row: size_mapping.get((row["Outlet_Location_Type"], row["Outlet_Type"]), row["Outlet_Size"]),
    axis=1
)

In [29]:
x = df.drop(["Item_Weight", "Outlet_Size", "Item_Outlet_Sales"], axis=1)
y = df["Item_Outlet_Sales"]

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [98]:
from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(X_train, y_train)

In [99]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [140]:
class CustomImputer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.item_mean = None
        self.overall_mean = None
        self.group_modes = None
        self.type_modes = None

    def fit(self, X, y=None):
        # Step 1: Store mean per Item_Identifier and overall mean.
        self.item_mean = X.groupby("Item_Identifier")["Item_Weight"].mean()
        self.overall_mean = X["Item_Weight"].mean()

        # Step 2: Store mode by (Location, Type) and by only Type
        self.group_modes = (
            X.groupby(["Outlet_Location_Type", "Outlet_Type"])["Outlet_Size"]
            .agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
        )
        self.type_modes = (
            X.groupby(["Outlet_Type"])["Outlet_Size"]
            .agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
        )
        return self

    def transform(self, X):
        X = X.copy()

        # --- Item_Weight Imputation ---
        X["Item_Weight"] = X.apply(
            lambda row: self.item_mean.get(row["Item_Identifier"], np.nan)
            if pd.isnull(row["Item_Weight"]) else row["Item_Weight"],
            axis=1
        )
        X["Item_Weight"] = X["Item_Weight"].fillna(self.overall_mean)

        # --- Outlet_Size Imputation ---
        def fill_outlet_size(row):
            if pd.isnull(row["Outlet_Size"]):
                val = self.group_modes.get((row["Outlet_Location_Type"], row["Outlet_Type"]), np.nan)
                if pd.isnull(val):
                    val = self.type_modes.get(row["Outlet_Type"], np.nan)
                if pd.isnull(val):
                    val = "Unknown"
                return val
            return row["Outlet_Size"]

        X["Outlet_Size"] = X.apply(fill_outlet_size, axis=1)

        # ====== Handle Item_Visibility ======
        # Replace 0 with NaN
        X["Item_Visibility"].replace(0, np.nan, inplace=True)
        
        # Fill with mean visibility per Item_Identifier
        X["Item_Visibility"] = X.groupby("Item_Identifier")["Item_Visibility"].transform(
            lambda x: x.fillna(x.mean())
        )
        
        # Still NaN? Fill with overall mean
        X["Item_Visibility"].fillna(X["Item_Visibility"].mean(), inplace=True)
        
        # Cap extreme values at 99th percentile
        q99 = X["Item_Visibility"].quantile(0.99)
        X.loc[X["Item_Visibility"] > q99, "Item_Visibility"] = q99


        # # --- Fix inconsistent categories in Item_Fat_Content ---
        X["Item_Fat_Content"] = X["Item_Fat_Content"].replace({"low fat": "Low Fat","LF": "Low Fat","reg": "Regular"})

        
        # --- Final fallback for any leftover missing ---
        for col in X.columns:
            if X[col].dtype == "object":
                X[col] = X[col].fillna("Unknown")
            else:
                X[col] = X[col].fillna(0)

        return X

In [141]:
df1= pd.read_csv("train.csv")

In [142]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("imputer", CustomImputer())
    # later steps like encoding, scaling, regression, etc.
])

df1= pipeline.fit_transform(df1)

In [143]:
df1.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [131]:
df.head(30)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,12.600,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,Small,Tier 2,Supermarket Type1,4710.5350
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Medium,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Medium,Tier 1,Supermarket Type1,2145.2076
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Medium,Tier 1,Supermarket Type1,1547.3192
16,NCB42,11.800,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
17,FDP49,9.000,Regular,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1,718.3982
18,DRI11,12.600,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224
20,FDN22,18.850,Regular,0.138190,Snack Foods,250.8724,OUT013,1987,High,Tier 3,Supermarket Type1,3775.0860
21,FDW12,12.600,Regular,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3,4064.0432
22,NCB30,14.600,Low Fat,0.025698,Household,196.5084,OUT035,2004,Small,Tier 2,Supermarket Type1,1587.2672
23,FDC37,12.600,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876
24,FDR28,13.850,Regular,0.025896,Frozen Foods,165.0210,OUT046,1997,Medium,Tier 1,Supermarket Type1,4078.0250
25,NCD06,13.000,Low Fat,0.099887,Household,45.9060,OUT017,2007,Small,Tier 2,Supermarket Type1,838.9080
26,FDV10,7.645,Regular,0.066693,Snack Foods,42.3112,OUT035,2004,Small,Tier 2,Supermarket Type1,1065.2800
27,DRJ59,11.650,low fat,0.019356,Hard Drinks,39.1164,OUT013,1987,High,Tier 3,Supermarket Type1,308.9312
28,FDE51,5.925,Regular,0.161467,Dairy,45.5086,OUT010,1998,Small,Tier 3,Grocery Store,178.4344
29,FDC14,12.600,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362

In [144]:
df1["Item_Fat_Content"].value_counts()

Item_Fat_Content
Low Fat    5517
Regular    3006
Name: count, dtype: int64

In [150]:
df1['New_Item_type'] = df1['Item_Identifier'].apply(lambda x: x[:2])
df1['New_Item_type'] = df1['New_Item_type'].map({'FD':'FOOD','NC':'Non-Consumable','DR':'Drinks'})
df1['New_Item_type'].value_counts()

New_Item_type
FOOD              6125
Non-Consumable    1599
Drinks             799
Name: count, dtype: int64

In [154]:
df1.loc[df1['New_Item_type']=='Non-Consumable','Item_Fat_Content'] = 'Non-Edible'
df1['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat       3918
Regular       3006
Non-Edible    1599
Name: count, dtype: int64

In [157]:
# creat small values for estasblisment years  max value is 2009 so we can sunstrace from 2010 but the data was collected in 2013 so it is safe to substracct from 2013
df1['Outlet_age'] = 2013 -  df1['Outlet_Establishment_Year']
df1['Outlet_age']

0       1999
1       2009
2       1999
3       1998
4       1987
        ...
8518    1987
8519    2002
8520    2004
8521    2009
8522    1997
Name: Outlet_age, Length: 8523, dtype: int64

In [158]:
# 1. Item Age (years since manufacturing)
df1['Item_Age'] = 2013 - df1['Item_Identifier'].str.extract(r'(\d+)').astype(float)

In [163]:
# 2. Outlet Age (years since establishment)
df1['Outlet_Age'] = 2013 - df1['Outlet_Establishment_Year']

In [164]:
# 3. Visibility Ratio (visibility compared to average of that item)
df1['Visibility_Avg'] = df1.groupby('Item_Identifier')['Item_Visibility'].transform('mean')
df1['Visibility_Ratio'] = df1['Item_Visibility'] / df1['Visibility_Avg']

In [165]:
# 4. Log-transform of Item_MRP (to reduce skewness)
df1['Item_MRP_Log'] = np.log1p(df1['Item_MRP'])

In [167]:
# 5. Interaction Features
df1['Item_Weight_x_Item_Visibility'] = df1['Item_Weight'] * df1['Item_Visibility']
df1['Item_Weight_x_Outlet_Age'] = df1['Item_Weight'] * df1['Outlet_Age']
df1['MRP_x_Visibility'] = df1['Item_MRP'] * df1['Item_Visibility']
# Interaction of visibility with Outlet_Size
df1['Visibility_x_Size'] = df1['Item_Visibility'] * df1['Outlet_Size'].map({'Small':1, 'Medium':2, 'High':3})

# Interaction of visibility with Outlet_Location_Type (Tier)
df1['Visibility_x_Tier'] = df1['Item_Visibility'] * df1['Outlet_Location_Type'].map({'Tier 1':1, 'Tier 2':2, 'Tier 3':3})

# Interaction of visibility with Outlet_Type (supermarket/grocery)
df1['Visibility_x_OutletType'] = df1['Item_Visibility'].astype(float) * df1['Outlet_Type'].astype('category').cat.codes